### ISSUE TITLE
a question 

### ISSUE THREAD

**Issue by XahidEx** [G3root/personal-site#1]
Have you tried opensea API again?

**Comment by G3root** [comment]
> Have you tried opensea API again?

yeah but couldn't get the api key

**Comment by XahidEx** [comment]
You inspired me. I have so many NFTs. So I'm also having difficulties with this issue. But I think I found something which might give you some ideas. I couldn't catch the problem. When you have time, Have a look at this repo https://github.com/amirardalan/synapsekit.com

**Comment by XahidEx** [comment]
Found the issue. Requests to this endpoint require an API key. If you don't have an API key, please [request one](https://docs.opensea.io/reference/request-an-api-key).
source: https://docs.opensea.io/reference/getting-assets

**Comment by G3root** [comment]
thanks for the suggestion ❤️ . i'll look on to it
